apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260612-155113-26r8e27h0dzm-service
spec:
  selector:
    app: enterprise-system-20260612-155113-26r8e27h0dzm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
